# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.cache/wt [current_project]
set_property parent.project_path C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/ip_repo/Image_sensor_DMA_1.0
  c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/ip_repo/image_sensor_dma_1.0
  c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/ip_repo/image_ctl_1.0
  c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/ip_repo/sensor_ctl_1.0
  c:/01_FPGA_project/Image_sensor/18_an5642_lwip_double/repo
} [current_project]
set_property ip_output_repo c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.dcp
set_property used_in_implementation false [get_files c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.dcp]
add_files -quiet c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.dcp
set_property used_in_implementation false [get_files c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.dcp]
add_files -quiet c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1.dcp
set_property used_in_implementation false [get_files c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1.dcp]
read_verilog -library xil_defaultlib C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/constrs_1/new/system.xdc]

read_xdc C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/constrs_1/new/an5642.xdc
set_property used_in_implementation false [get_files C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/constrs_1/new/an5642.xdc]


synth_design -top system_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
