set_property SRC_FILE_INFO {cfile:C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/constrs_1/new/system.xdc rfile:../../../image_open_source.srcs/constrs_1/new/system.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/01_FPGA_project/Image_sensor/Image_transfer_open_source/image_open_source/image_open_source.srcs/constrs_1/new/an5642.xdc rfile:../../../image_open_source.srcs/constrs_1/new/an5642.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports pl_clk]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[0]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[1]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[2]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[3]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[4]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[5]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[6]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[7]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[8]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[9]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[10]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[11]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[12]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[13]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[14]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[15]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[16]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[17]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[18]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[19]} {system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/Cnt_start[20]}]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/image_ctl_0_Mode[0]} {system_i/image_ctl_0_Mode[1]}]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/image_ctl_0_Cstart]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/image_ctl_0_Expo_start]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list system_i/image_ctl_0_Frame_done]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list system_i/image_ctl_0_ipor]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list system_i/image_ctl_0_mdd]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list system_i/ocompclk_1]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list system_i/oisadc_1]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/s00_axi_aresetn]]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list system_i/image_ctl_0/inst/image_ctl_v1_0_S00_AXI_inst/SensorCtrl_top/SensorCtrl0/start_up_r1]]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18     [get_ports {sensor_out[3]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15     [get_ports {sensor_out[2]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13     [get_ports {sensor_out[1]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13     [get_ports {sensor_out[0]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14     [get_ports {Pod[15]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16     [get_ports {Pod[14]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15     [get_ports {Pod[13]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14    [get_ports {Pod[12]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17     [get_ports {Pod[11]}]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14     [get_ports {Pod[10]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15     [get_ports {Pod[9]}]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16     [get_ports {Pod[8]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17     [get_ports {Pod[7]}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16     [get_ports {Pod[6]}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15     [get_ports {Pod[5]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18     [get_ports {Pod[4]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14     [get_ports {Pod[3]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15     [get_ports {Pod[2]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17     [get_ports {Pod[1]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14     [get_ports {Pod[0]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19     [get_ports {ocompclk}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18     [get_ports {oisadc}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U13 [get_ports {ipor}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports {Cstart}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {Mode[1]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports {Mode[0]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {mdd}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {Expo_Ctrl}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {Enb}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports {clk_10M}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   J19   [get_ports {Pod1[15]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   K19   [get_ports {Pod1[14]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   H20   [get_ports {Pod1[13]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   J20   [get_ports {Pod1[12]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   L17   [get_ports {Pod1[11]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   L16   [get_ports {Pod1[10]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   M18   [get_ports {Pod1[9]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   M17   [get_ports {Pod1[8]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   D20   [get_ports {Pod1[7]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   D19   [get_ports {Pod1[6]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   E19   [get_ports {Pod1[5]}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   E18   [get_ports {Pod1[4]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   G18   [get_ports {Pod1[3]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   G17   [get_ports {Pod1[2]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   H17   [get_ports {Pod1[1]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   H16   [get_ports {Pod1[0]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   J14   [get_ports {ocompclk1}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   K14   [get_ports {oisadc1}]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {ipor1}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports {Cstart1}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {Mode1[1]}]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports {Mode1[0]}]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {mdd1}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {Expo_Ctrl1}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports {Enb1}]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {clk_10M1}]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {Frame_done}]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {Expo_start}]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {Frame_done1}]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports {Expo_start1}]
