
set_property PACKAGE_PIN V18     [get_ports {sensor_out[3]}]
set_property PACKAGE_PIN T15     [get_ports {sensor_out[2]}]
set_property PACKAGE_PIN V13     [get_ports {sensor_out[1]}]
set_property PACKAGE_PIN W13     [get_ports {sensor_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sensor_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sensor_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sensor_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sensor_out[0]}]

set_property PACKAGE_PIN P14     [get_ports {Pod[15]}]
set_property PACKAGE_PIN Y16     [get_ports {Pod[14]}]
set_property PACKAGE_PIN V15     [get_ports {Pod[13]}]
set_property PACKAGE_PIN W14    [get_ports {Pod[12]}]
set_property PACKAGE_PIN N17     [get_ports {Pod[11]}]
set_property PACKAGE_PIN U14     [get_ports {Pod[10]}]
set_property PACKAGE_PIN P15     [get_ports {Pod[9]}]
set_property PACKAGE_PIN T16     [get_ports {Pod[8]}]
set_property PACKAGE_PIN U17     [get_ports {Pod[7]}]
set_property PACKAGE_PIN P16     [get_ports {Pod[6]}]
set_property PACKAGE_PIN U15     [get_ports {Pod[5]}]
set_property PACKAGE_PIN P18     [get_ports {Pod[4]}]
set_property PACKAGE_PIN Y14     [get_ports {Pod[3]}]
set_property PACKAGE_PIN W15     [get_ports {Pod[2]}]
set_property PACKAGE_PIN Y17     [get_ports {Pod[1]}]
set_property PACKAGE_PIN R14     [get_ports {Pod[0]}]

set_property PACKAGE_PIN W19     [get_ports {ocompclk}]
set_property PACKAGE_PIN W18     [get_ports {oisadc}]

set_property IOSTANDARD LVCMOS33 [get_ports {Pod[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ocompclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {oisadc}]


set_property PACKAGE_PIN U13 [get_ports {ipor}]
set_property PACKAGE_PIN T11 [get_ports {Cstart}]
set_property PACKAGE_PIN B19 [get_ports {Mode[1]}]
set_property PACKAGE_PIN T14 [get_ports {Mode[0]}]
set_property PACKAGE_PIN C20 [get_ports {mdd}]
set_property PACKAGE_PIN V12 [get_ports {Expo_Ctrl}]
set_property PACKAGE_PIN V17 [get_ports {Enb}]


set_property IOSTANDARD LVCMOS33 [get_ports {ipor}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cstart}]
set_property IOSTANDARD LVCMOS33 [get_ports {Mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdd}]
set_property IOSTANDARD LVCMOS33 [get_ports {Expo_Ctrl}]
set_property IOSTANDARD LVCMOS33 [get_ports {Enb}]

set_property PACKAGE_PIN T12 [get_ports {clk_10M}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_10M}]



set_property PACKAGE_PIN   J19   [get_ports {Pod1[15]}]
set_property PACKAGE_PIN   K19   [get_ports {Pod1[14]}]
set_property PACKAGE_PIN   H20   [get_ports {Pod1[13]}]
set_property PACKAGE_PIN   J20   [get_ports {Pod1[12]}]
set_property PACKAGE_PIN   L17   [get_ports {Pod1[11]}]
set_property PACKAGE_PIN   L16   [get_ports {Pod1[10]}]
set_property PACKAGE_PIN   M18   [get_ports {Pod1[9]}]
set_property PACKAGE_PIN   M17   [get_ports {Pod1[8]}]
set_property PACKAGE_PIN   D20   [get_ports {Pod1[7]}]
set_property PACKAGE_PIN   D19   [get_ports {Pod1[6]}]
set_property PACKAGE_PIN   E19   [get_ports {Pod1[5]}]
set_property PACKAGE_PIN   E18   [get_ports {Pod1[4]}]
set_property PACKAGE_PIN   G18   [get_ports {Pod1[3]}]
set_property PACKAGE_PIN   G17   [get_ports {Pod1[2]}]
set_property PACKAGE_PIN   H17   [get_ports {Pod1[1]}]
set_property PACKAGE_PIN   H16   [get_ports {Pod1[0]}]

set_property PACKAGE_PIN   J14   [get_ports {ocompclk1}]
set_property PACKAGE_PIN   K14   [get_ports {oisadc1}]

set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Pod1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ocompclk1}]
set_property IOSTANDARD LVCMOS33 [get_ports {oisadc1}]



set_property PACKAGE_PIN F20 [get_ports {ipor1}]
set_property PACKAGE_PIN F19 [get_ports {Cstart1}]
set_property PACKAGE_PIN G20 [get_ports {Mode1[1]}]
set_property PACKAGE_PIN G19 [get_ports {Mode1[0]}]
set_property PACKAGE_PIN H18 [get_ports {mdd1}]
set_property PACKAGE_PIN J18 [get_ports {Expo_Ctrl1}]
set_property PACKAGE_PIN L20 [get_ports {Enb1}]

set_property IOSTANDARD LVCMOS33 [get_ports {ipor1}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cstart1}]
set_property IOSTANDARD LVCMOS33 [get_ports {Mode1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Mode1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdd1}]
set_property IOSTANDARD LVCMOS33 [get_ports {Expo_Ctrl1}]
set_property IOSTANDARD LVCMOS33 [get_ports {Enb1}]

set_property PACKAGE_PIN K17 [get_ports {clk_10M1}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_10M1}]


set_property PACKAGE_PIN A20 [get_ports {Frame_done}]
set_property PACKAGE_PIN B20 [get_ports {Expo_start}]
set_property IOSTANDARD LVCMOS33 [get_ports {Frame_done}]
set_property IOSTANDARD LVCMOS33 [get_ports {Expo_start}]


set_property PACKAGE_PIN F17 [get_ports {Frame_done1}]
set_property PACKAGE_PIN F16 [get_ports {Expo_start1}]
set_property IOSTANDARD LVCMOS33 [get_ports {Frame_done1}]
set_property IOSTANDARD LVCMOS33 [get_ports {Expo_start1}]

#set_property PULLUP true [get_ports cmos1_i2c_scl_io]
#set_property PULLUP true [get_ports cmos1_i2c_sda_io]
#set_property PULLUP true [get_ports cmos2_i2c_scl_io]
#set_property PULLUP true [get_ports cmos2_i2c_sda_io]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos2_pclk_IBUF]